### ISSUE TITLE
[🐛 | Bug] Toggle visibility in inputs password with Edge is displayed twice

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/megashark-lib#130]
![Image](https://github.com/user-attachments/assets/5850f0a7-c10b-47e6-bc30-d8dde7cb4c1c)

**Comment by NicoTuxx** [comment]
Can't seem to reproduce.

Solution is quite simple https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#visibility-of-the-control so Ionic should be doing it for us already.
